# This is a basic workflow to help you get started with Actions

name: Windows_BuildV8

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: master
  pull_request:
    branches: master
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: V8/V8

      # Runs a single command using the runners shell
      - name: download depot_tools
      - shell: cmd
        run: |
          wget https://storage.googleapis.com/chrome-infra/depot_tools.zip
          
      # unzip depot_tools
      - name: unzip depot_tools
      - shell: powershell
        run: |
          Expand-Archive -Force ./depot_tools.zip ./
          
      # add depot_tools & VS2019 to PATH
      - name: add depot_tools & VS2019 to PATH
      - shell: cmd
        run: |
          setx /M path "%path%;%%~dp0%\depot_tools"
          setx /M vs2019_install "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
          echo %path%
          echo %vs2019_install%
      
        
      
